### ISSUE TITLE
What font is used in the screenshots?

### ISSUE THREAD

**Issue by zmjackson** [polirritmico/monokai-nightasty.nvim#2]
Great theme. I also really like the font you're using in the screenshots, what is it?

Thanks!

**Comment by polirritmico** [comment]
Hi. Thanks for the kind words.

The font is the [Fira Code Nerd Font](https://www.nerdfonts.com/font-downloads).
For the screenshot I'm using the medium width in Konsole.

I don't like the `@` and the `&` characters of the default settings so I use the [variants glyphs](https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets) (`ss03` and `ss05`) changed with this tool: [FontFreezer](https://mutsuntsai.github.io/fontfreeze)
