### ISSUE TITLE
get_version crashes on nixos

### ISSUE THREAD

**Issue by IvanTurgenev** [polirritmico/monokai-nightasty.nvim#3]
.git folder is not included it seems when builded with `pkgs.vimUtils.buildVimPlugin ` after hardcoding get variable it works fine. Idk how prevalent that way is for setting version of what that variable is for, but first time i see a plugin crashing with the nix build process.

**Comment by polirritmico** [comment]
Hi! Thanks for using the plugin and for taking the time to submit the bug report. In case you were wondering, that variable was used to force the cache generation.

In any case, the issue should be resolved by 4ac0d9f. Since I don’t use Nix myself, could you please confirm if it’s working for you?

**Comment by IvanTurgenev** [comment]
Looks good thanks
